# Fase 1: build dell'app Angular
FROM node:18 AS build
WORKDIR /frontend
COPY . .
RUN npm install
RUN npm run build

# Fase 2: serve l'app con NGINX
FROM nginx:alpine
COPY --from=build /frontend/dist/scout-firenze-site/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
